name = "memos-worker"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "YOUR_D1_DATABASE_ID"
database_name = "YOUR_D1_DATABASE_NAME"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "YOUR_KV_NAMESPACE_ID"
preview_id = ""

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "memos-bucket"
# preview_bucket_name = "notes-files-preview"
